name: Run Telegram Alerts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: zibdie/pastebinproalertbot:latest
        env:
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          SERVER_MODE: true
    steps:
      - name: Check environment
        run: echo "Environment variables are set and container is up and running"
