name: Run Telegram Alerts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: zibdie/pastebinproalertbot:latest
        env:
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          SERVER_MODE: true
    steps:
      - name: Run container
        run: docker run -e CHAT_ID=$CHAT_ID -e BOT_TOKEN=$BOT_TOKEN -e SERVER_MODE=$SERVER_MODE zibdie/pastebinproalertbot:latest
